name: BuildComp
main: io.github.io.F9Alejandro.BuildComp.main
version: 0.0.1
author: [F9Alejandro,Empire92]
website: www.empcraft.com
softdepend: [Essentials]
depend: [WorldEdit,Worldguard]
commands:
   buco:
      description: BuildComp commands
   buildcomp:
      description: BuildComp commands
   buildcompetition:
      description: BuildComp commands