name: BuildComp
main: io.github.F9Alejandro.BuildComp.BuildComp
version: 0.0.1
author: [F9Alejandro,Empire92]
website: www.empcraft.com
softdepend: [Essentials]
commands:
   buco:
      description: BuildComp commands
   buildcomp:
      description: BuildComp commands
   buildcompetition:
      description: BuildComp commands